package module

// GlobalStatus
// mysql -e "SHOW GLOBAL STATUS" |awk '{print $1 " string `json:"}'|sed -r 's/(^|_)([a-z])/\U\2/g' > file1.txt
// mysql -e "SHOW GLOBAL STATUS" |awk '{print tolower($1)"\"`"}' > file2.txt
// paste -d\" file1.txt file2.txt < /dev/null
type GlobalStatus struct {
	AbortedClients                                  string `json:"aborted_clients"`
	AbortedConnects                                 string `json:"aborted_connects"`
	AclCacheItemsCount                              string `json:"acl_cache_items_count"`
	BinlogCacheDiskUse                              string `json:"binlog_cache_disk_use"`
	BinlogCacheUse                                  string `json:"binlog_cache_use"`
	BinlogStmtCacheDiskUse                          string `json:"binlog_stmt_cache_disk_use"`
	BinlogStmtCacheUse                              string `json:"binlog_stmt_cache_use"`
	BytesReceived                                   string `json:"bytes_received"`
	BytesSent                                       string `json:"bytes_sent"`
	CachingSha2PasswordRsaPublicKey                 string `json:"caching_sha2_password_rsa_public_key"`
	ComAdminCommands                                string `json:"com_admin_commands"`
	ComAssignToKeycache                             string `json:"com_assign_to_keycache"`
	ComAlterDb                                      string `json:"com_alter_db"`
	ComAlterEvent                                   string `json:"com_alter_event"`
	ComAlterFunction                                string `json:"com_alter_function"`
	ComAlterInstance                                string `json:"com_alter_instance"`
	ComAlterProcedure                               string `json:"com_alter_procedure"`
	ComAlterResourceGroup                           string `json:"com_alter_resource_group"`
	ComAlterServer                                  string `json:"com_alter_server"`
	ComAlterTable                                   string `json:"com_alter_table"`
	ComAlterTablespace                              string `json:"com_alter_tablespace"`
	ComAlterUser                                    string `json:"com_alter_user"`
	ComAlterUserDefaultRole                         string `json:"com_alter_user_default_role"`
	ComAnalyze                                      string `json:"com_analyze"`
	ComBegin                                        string `json:"com_begin"`
	ComBinlog                                       string `json:"com_binlog"`
	ComCallProcedure                                string `json:"com_call_procedure"`
	ComChangeDb                                     string `json:"com_change_db"`
	ComChangeMaster                                 string `json:"com_change_master"`
	ComChangeReplFilter                             string `json:"com_change_repl_filter"`
	ComChangeReplicationSource                      string `json:"com_change_replication_source"`
	ComCheck                                        string `json:"com_check"`
	ComChecksum                                     string `json:"com_checksum"`
	ComClone                                        string `json:"com_clone"`
	ComCommit                                       string `json:"com_commit"`
	ComCreateDb                                     string `json:"com_create_db"`
	ComCreateEvent                                  string `json:"com_create_event"`
	ComCreateFunction                               string `json:"com_create_function"`
	ComCreateIndex                                  string `json:"com_create_index"`
	ComCreateProcedure                              string `json:"com_create_procedure"`
	ComCreateRole                                   string `json:"com_create_role"`
	ComCreateServer                                 string `json:"com_create_server"`
	ComCreateTable                                  string `json:"com_create_table"`
	ComCreateResourceGroup                          string `json:"com_create_resource_group"`
	ComCreateTrigger                                string `json:"com_create_trigger"`
	ComCreateUdf                                    string `json:"com_create_udf"`
	ComCreateUser                                   string `json:"com_create_user"`
	ComCreateView                                   string `json:"com_create_view"`
	ComCreateSpatialReferenceSystem                 string `json:"com_create_spatial_reference_system"`
	ComDeallocSql                                   string `json:"com_dealloc_sql"`
	ComDelete                                       string `json:"com_delete"`
	ComDeleteMulti                                  string `json:"com_delete_multi"`
	ComDo                                           string `json:"com_do"`
	ComDropDb                                       string `json:"com_drop_db"`
	ComDropEvent                                    string `json:"com_drop_event"`
	ComDropFunction                                 string `json:"com_drop_function"`
	ComDropIndex                                    string `json:"com_drop_index"`
	ComDropProcedure                                string `json:"com_drop_procedure"`
	ComDropResourceGroup                            string `json:"com_drop_resource_group"`
	ComDropRole                                     string `json:"com_drop_role"`
	ComDropServer                                   string `json:"com_drop_server"`
	ComDropSpatialReferenceSystem                   string `json:"com_drop_spatial_reference_system"`
	ComDropTable                                    string `json:"com_drop_table"`
	ComDropTrigger                                  string `json:"com_drop_trigger"`
	ComDropUser                                     string `json:"com_drop_user"`
	ComDropView                                     string `json:"com_drop_view"`
	ComEmptyQuery                                   string `json:"com_empty_query"`
	ComExecuteSql                                   string `json:"com_execute_sql"`
	ComExplainOther                                 string `json:"com_explain_other"`
	ComFlush                                        string `json:"com_flush"`
	ComGetDiagnostics                               string `json:"com_get_diagnostics"`
	ComGrant                                        string `json:"com_grant"`
	ComGrantRoles                                   string `json:"com_grant_roles"`
	ComHaClose                                      string `json:"com_ha_close"`
	ComHaOpen                                       string `json:"com_ha_open"`
	ComHaRead                                       string `json:"com_ha_read"`
	ComHelp                                         string `json:"com_help"`
	ComImport                                       string `json:"com_import"`
	ComInsert                                       string `json:"com_insert"`
	ComInsertSelect                                 string `json:"com_insert_select"`
	ComInstallComponent                             string `json:"com_install_component"`
	ComInstallPlugin                                string `json:"com_install_plugin"`
	ComKill                                         string `json:"com_kill"`
	ComLoad                                         string `json:"com_load"`
	ComLockInstance                                 string `json:"com_lock_instance"`
	ComLockTables                                   string `json:"com_lock_tables"`
	ComOptimize                                     string `json:"com_optimize"`
	ComPreloadKeys                                  string `json:"com_preload_keys"`
	ComPrepareSql                                   string `json:"com_prepare_sql"`
	ComPurge                                        string `json:"com_purge"`
	ComPurgeBeforeDate                              string `json:"com_purge_before_date"`
	ComReleaseSavepoint                             string `json:"com_release_savepoint"`
	ComRenameTable                                  string `json:"com_rename_table"`
	ComRenameUser                                   string `json:"com_rename_user"`
	ComRepair                                       string `json:"com_repair"`
	ComReplace                                      string `json:"com_replace"`
	ComReplaceSelect                                string `json:"com_replace_select"`
	ComReset                                        string `json:"com_reset"`
	ComResignal                                     string `json:"com_resignal"`
	ComRestart                                      string `json:"com_restart"`
	ComRevoke                                       string `json:"com_revoke"`
	ComRevokeAll                                    string `json:"com_revoke_all"`
	ComRevokeRoles                                  string `json:"com_revoke_roles"`
	ComRollback                                     string `json:"com_rollback"`
	ComRollbackToSavepoint                          string `json:"com_rollback_to_savepoint"`
	ComSavepoint                                    string `json:"com_savepoint"`
	ComSelect                                       string `json:"com_select"`
	ComSetOption                                    string `json:"com_set_option"`
	ComSetPassword                                  string `json:"com_set_password"`
	ComSetResourceGroup                             string `json:"com_set_resource_group"`
	ComSetRole                                      string `json:"com_set_role"`
	ComSignal                                       string `json:"com_signal"`
	ComShowBinlogEvents                             string `json:"com_show_binlog_events"`
	ComShowBinlogs                                  string `json:"com_show_binlogs"`
	ComShowCharsets                                 string `json:"com_show_charsets"`
	ComShowCollations                               string `json:"com_show_collations"`
	ComShowCreateDb                                 string `json:"com_show_create_db"`
	ComShowCreateEvent                              string `json:"com_show_create_event"`
	ComShowCreateFunc                               string `json:"com_show_create_func"`
	ComShowCreateProc                               string `json:"com_show_create_proc"`
	ComShowCreateTable                              string `json:"com_show_create_table"`
	ComShowCreateTrigger                            string `json:"com_show_create_trigger"`
	ComShowDatabases                                string `json:"com_show_databases"`
	ComShowEngineLogs                               string `json:"com_show_engine_logs"`
	ComShowEngineMutex                              string `json:"com_show_engine_mutex"`
	ComShowEngineStatus                             string `json:"com_show_engine_status"`
	ComShowEvents                                   string `json:"com_show_events"`
	ComShowErrors                                   string `json:"com_show_errors"`
	ComShowFields                                   string `json:"com_show_fields"`
	ComShowFunctionCode                             string `json:"com_show_function_code"`
	ComShowFunctionStatus                           string `json:"com_show_function_status"`
	ComShowGrants                                   string `json:"com_show_grants"`
	ComShowKeys                                     string `json:"com_show_keys"`
	ComShowMasterStatus                             string `json:"com_show_master_status"`
	ComShowOpenTables                               string `json:"com_show_open_tables"`
	ComShowPlugins                                  string `json:"com_show_plugins"`
	ComShowPrivileges                               string `json:"com_show_privileges"`
	ComShowProcedureCode                            string `json:"com_show_procedure_code"`
	ComShowProcedureStatus                          string `json:"com_show_procedure_status"`
	ComShowProcesslist                              string `json:"com_show_processlist"`
	ComShowProfile                                  string `json:"com_show_profile"`
	ComShowProfiles                                 string `json:"com_show_profiles"`
	ComShowRelaylogEvents                           string `json:"com_show_relaylog_events"`
	ComShowReplicas                                 string `json:"com_show_replicas"`
	ComShowSlaveHosts                               string `json:"com_show_slave_hosts"`
	ComShowReplicaStatus                            string `json:"com_show_replica_status"`
	ComShowSlaveStatus                              string `json:"com_show_slave_status"`
	ComShowStatus                                   string `json:"com_show_status"`
	ComShowStorageEngines                           string `json:"com_show_storage_engines"`
	ComShowTableStatus                              string `json:"com_show_table_status"`
	ComShowTables                                   string `json:"com_show_tables"`
	ComShowTriggers                                 string `json:"com_show_triggers"`
	ComShowVariables                                string `json:"com_show_variables"`
	ComShowWarnings                                 string `json:"com_show_warnings"`
	ComShowCreateUser                               string `json:"com_show_create_user"`
	ComShutdown                                     string `json:"com_shutdown"`
	ComReplicaStart                                 string `json:"com_replica_start"`
	ComSlaveStart                                   string `json:"com_slave_start"`
	ComReplicaStop                                  string `json:"com_replica_stop"`
	ComSlaveStop                                    string `json:"com_slave_stop"`
	ComGroupReplicationStart                        string `json:"com_group_replication_start"`
	ComGroupReplicationStop                         string `json:"com_group_replication_stop"`
	ComStmtExecute                                  string `json:"com_stmt_execute"`
	ComStmtClose                                    string `json:"com_stmt_close"`
	ComStmtFetch                                    string `json:"com_stmt_fetch"`
	ComStmtPrepare                                  string `json:"com_stmt_prepare"`
	ComStmtReset                                    string `json:"com_stmt_reset"`
	ComStmtSendLongData                             string `json:"com_stmt_send_long_data"`
	ComTruncate                                     string `json:"com_truncate"`
	ComUninstallComponent                           string `json:"com_uninstall_component"`
	ComUninstallPlugin                              string `json:"com_uninstall_plugin"`
	ComUnlockInstance                               string `json:"com_unlock_instance"`
	ComUnlockTables                                 string `json:"com_unlock_tables"`
	ComUpdate                                       string `json:"com_update"`
	ComUpdateMulti                                  string `json:"com_update_multi"`
	ComXaCommit                                     string `json:"com_xa_commit"`
	ComXaEnd                                        string `json:"com_xa_end"`
	ComXaPrepare                                    string `json:"com_xa_prepare"`
	ComXaRecover                                    string `json:"com_xa_recover"`
	ComXaRollback                                   string `json:"com_xa_rollback"`
	ComXaStart                                      string `json:"com_xa_start"`
	ComStmtReprepare                                string `json:"com_stmt_reprepare"`
	ConnectionErrorsAccept                          string `json:"connection_errors_accept"`
	ConnectionErrorsInternal                        string `json:"connection_errors_internal"`
	ConnectionErrorsMaxConnections                  string `json:"connection_errors_max_connections"`
	ConnectionErrorsPeerAddress                     string `json:"connection_errors_peer_address"`
	ConnectionErrorsSelect                          string `json:"connection_errors_select"`
	ConnectionErrorsTcpwrap                         string `json:"connection_errors_tcpwrap"`
	Connections                                     string `json:"connections"`
	CreatedTmpDiskTables                            string `json:"created_tmp_disk_tables"`
	CreatedTmpFiles                                 string `json:"created_tmp_files"`
	CreatedTmpTables                                string `json:"created_tmp_tables"`
	CurrentTlsCa                                    string `json:"current_tls_ca"`
	CurrentTlsCapath                                string `json:"current_tls_capath"`
	CurrentTlsCert                                  string `json:"current_tls_cert"`
	CurrentTlsCipher                                string `json:"current_tls_cipher"`
	CurrentTlsCiphersuites                          string `json:"current_tls_ciphersuites"`
	CurrentTlsCrl                                   string `json:"current_tls_crl"`
	CurrentTlsCrlpath                               string `json:"current_tls_crlpath"`
	CurrentTlsKey                                   string `json:"current_tls_key"`
	CurrentTlsVersion                               string `json:"current_tls_version"`
	DelayedErrors                                   string `json:"delayed_errors"`
	DelayedInsertThreads                            string `json:"delayed_insert_threads"`
	DelayedWrites                                   string `json:"delayed_writes"`
	ErrorLogBufferedBytes                           string `json:"error_log_buffered_bytes"`
	ErrorLogBufferedEvents                          string `json:"error_log_buffered_events"`
	ErrorLogExpiredEvents                           string `json:"error_log_expired_events"`
	ErrorLogLatestWrite                             string `json:"error_log_latest_write"`
	FlushCommands                                   string `json:"flush_commands"`
	HandlerCommit                                   string `json:"handler_commit"`
	HandlerDelete                                   string `json:"handler_delete"`
	HandlerDiscover                                 string `json:"handler_discover"`
	HandlerExternalLock                             string `json:"handler_external_lock"`
	HandlerMrrInit                                  string `json:"handler_mrr_init"`
	HandlerPrepare                                  string `json:"handler_prepare"`
	HandlerReadFirst                                string `json:"handler_read_first"`
	HandlerReadKey                                  string `json:"handler_read_key"`
	HandlerReadLast                                 string `json:"handler_read_last"`
	HandlerReadNext                                 string `json:"handler_read_next"`
	HandlerReadPrev                                 string `json:"handler_read_prev"`
	HandlerReadRnd                                  string `json:"handler_read_rnd"`
	HandlerReadRndNext                              string `json:"handler_read_rnd_next"`
	HandlerRollback                                 string `json:"handler_rollback"`
	HandlerSavepoint                                string `json:"handler_savepoint"`
	HandlerSavepointRollback                        string `json:"handler_savepoint_rollback"`
	HandlerUpdate                                   string `json:"handler_update"`
	HandlerWrite                                    string `json:"handler_write"`
	InnodbBufferPoolDumpStatus                      string `json:"innodb_buffer_pool_dump_status"`
	InnodbBufferPoolLoadStatus                      string `json:"innodb_buffer_pool_load_status"`
	InnodbBufferPoolResizeStatus                    string `json:"innodb_buffer_pool_resize_status"`
	InnodbBufferPoolPagesData                       string `json:"innodb_buffer_pool_pages_data"`
	InnodbBufferPoolBytesData                       string `json:"innodb_buffer_pool_bytes_data"`
	InnodbBufferPoolPagesDirty                      string `json:"innodb_buffer_pool_pages_dirty"`
	InnodbBufferPoolBytesDirty                      string `json:"innodb_buffer_pool_bytes_dirty"`
	InnodbBufferPoolPagesFlushed                    string `json:"innodb_buffer_pool_pages_flushed"`
	InnodbBufferPoolPagesFree                       string `json:"innodb_buffer_pool_pages_free"`
	InnodbBufferPoolPagesMisc                       string `json:"innodb_buffer_pool_pages_misc"`
	InnodbBufferPoolPagesTotal                      string `json:"innodb_buffer_pool_pages_total"`
	InnodbBufferPoolReadAheadRnd                    string `json:"innodb_buffer_pool_read_ahead_rnd"`
	InnodbBufferPoolReadAhead                       string `json:"innodb_buffer_pool_read_ahead"`
	InnodbBufferPoolReadAheadEvicted                string `json:"innodb_buffer_pool_read_ahead_evicted"`
	InnodbBufferPoolReadRequests                    string `json:"innodb_buffer_pool_read_requests"`
	InnodbBufferPoolReads                           string `json:"innodb_buffer_pool_reads"`
	InnodbBufferPoolWaitFree                        string `json:"innodb_buffer_pool_wait_free"`
	InnodbBufferPoolWriteRequests                   string `json:"innodb_buffer_pool_write_requests"`
	InnodbDataFsyncs                                string `json:"innodb_data_fsyncs"`
	InnodbDataPendingFsyncs                         string `json:"innodb_data_pending_fsyncs"`
	InnodbDataPendingReads                          string `json:"innodb_data_pending_reads"`
	InnodbDataPendingWrites                         string `json:"innodb_data_pending_writes"`
	InnodbDataRead                                  string `json:"innodb_data_read"`
	InnodbDataReads                                 string `json:"innodb_data_reads"`
	InnodbDataWrites                                string `json:"innodb_data_writes"`
	InnodbDataWritten                               string `json:"innodb_data_written"`
	InnodbDblwrPagesWritten                         string `json:"innodb_dblwr_pages_written"`
	InnodbDblwrWrites                               string `json:"innodb_dblwr_writes"`
	InnodbLogWaits                                  string `json:"innodb_log_waits"`
	InnodbLogWriteRequests                          string `json:"innodb_log_write_requests"`
	InnodbLogWrites                                 string `json:"innodb_log_writes"`
	InnodbOsLogFsyncs                               string `json:"innodb_os_log_fsyncs"`
	InnodbOsLogPendingFsyncs                        string `json:"innodb_os_log_pending_fsyncs"`
	InnodbOsLogPendingWrites                        string `json:"innodb_os_log_pending_writes"`
	InnodbOsLogWritten                              string `json:"innodb_os_log_written"`
	InnodbPageSize                                  string `json:"innodb_page_size"`
	InnodbPagesCreated                              string `json:"innodb_pages_created"`
	InnodbPagesRead                                 string `json:"innodb_pages_read"`
	InnodbPagesWritten                              string `json:"innodb_pages_written"`
	InnodbRedoLogEnabled                            string `json:"innodb_redo_log_enabled"`
	InnodbRowLockCurrentWaits                       string `json:"innodb_row_lock_current_waits"`
	InnodbRowLockTime                               string `json:"innodb_row_lock_time"`
	InnodbRowLockTimeAvg                            string `json:"innodb_row_lock_time_avg"`
	InnodbRowLockTimeMax                            string `json:"innodb_row_lock_time_max"`
	InnodbRowLockWaits                              string `json:"innodb_row_lock_waits"`
	InnodbRowsDeleted                               string `json:"innodb_rows_deleted"`
	InnodbRowsInserted                              string `json:"innodb_rows_inserted"`
	InnodbRowsRead                                  string `json:"innodb_rows_read"`
	InnodbRowsUpdated                               string `json:"innodb_rows_updated"`
	InnodbSystemRowsDeleted                         string `json:"innodb_system_rows_deleted"`
	InnodbSystemRowsInserted                        string `json:"innodb_system_rows_inserted"`
	InnodbSystemRowsRead                            string `json:"innodb_system_rows_read"`
	InnodbSystemRowsUpdated                         string `json:"innodb_system_rows_updated"`
	InnodbSampledPagesRead                          string `json:"innodb_sampled_pages_read"`
	InnodbSampledPagesSkipped                       string `json:"innodb_sampled_pages_skipped"`
	InnodbNumOpenFiles                              string `json:"innodb_num_open_files"`
	InnodbTruncatedStatusWrites                     string `json:"innodb_truncated_status_writes"`
	InnodbUndoTablespacesTotal                      string `json:"innodb_undo_tablespaces_total"`
	InnodbUndoTablespacesImplicit                   string `json:"innodb_undo_tablespaces_implicit"`
	InnodbUndoTablespacesExplicit                   string `json:"innodb_undo_tablespaces_explicit"`
	InnodbUndoTablespacesActive                     string `json:"innodb_undo_tablespaces_active"`
	KeyBlocksNotFlushed                             string `json:"key_blocks_not_flushed"`
	KeyBlocksUnused                                 string `json:"key_blocks_unused"`
	KeyBlocksUsed                                   string `json:"key_blocks_used"`
	KeyReadRequests                                 string `json:"key_read_requests"`
	KeyReads                                        string `json:"key_reads"`
	KeyWriteRequests                                string `json:"key_write_requests"`
	KeyWrites                                       string `json:"key_writes"`
	LockedConnects                                  string `json:"locked_connects"`
	MaxExecutionTimeExceeded                        string `json:"max_execution_time_exceeded"`
	MaxExecutionTimeSet                             string `json:"max_execution_time_set"`
	MaxExecutionTimeSetFailed                       string `json:"max_execution_time_set_failed"`
	MaxUsedConnections                              string `json:"max_used_connections"`
	MaxUsedConnectionsTime                          string `json:"max_used_connections_time"`
	MysqlxAbortedClients                            string `json:"mysqlx_aborted_clients"`
	MysqlxAddress                                   string `json:"mysqlx_address"`
	MysqlxBytesReceived                             string `json:"mysqlx_bytes_received"`
	MysqlxBytesReceivedCompressedPayload            string `json:"mysqlx_bytes_received_compressed_payload"`
	MysqlxBytesReceivedUncompressedFrame            string `json:"mysqlx_bytes_received_uncompressed_frame"`
	MysqlxBytesSent                                 string `json:"mysqlx_bytes_sent"`
	MysqlxBytesSentCompressedPayload                string `json:"mysqlx_bytes_sent_compressed_payload"`
	MysqlxBytesSentUncompressedFrame                string `json:"mysqlx_bytes_sent_uncompressed_frame"`
	MysqlxCompressionAlgorithm                      string `json:"mysqlx_compression_algorithm"`
	MysqlxCompressionLevel                          string `json:"mysqlx_compression_level"`
	MysqlxConnectionAcceptErrors                    string `json:"mysqlx_connection_accept_errors"`
	MysqlxConnectionErrors                          string `json:"mysqlx_connection_errors"`
	MysqlxConnectionsAccepted                       string `json:"mysqlx_connections_accepted"`
	MysqlxConnectionsClosed                         string `json:"mysqlx_connections_closed"`
	MysqlxConnectionsRejected                       string `json:"mysqlx_connections_rejected"`
	MysqlxCrudCreateView                            string `json:"mysqlx_crud_create_view"`
	MysqlxCrudDelete                                string `json:"mysqlx_crud_delete"`
	MysqlxCrudDropView                              string `json:"mysqlx_crud_drop_view"`
	MysqlxCrudFind                                  string `json:"mysqlx_crud_find"`
	MysqlxCrudInsert                                string `json:"mysqlx_crud_insert"`
	MysqlxCrudModifyView                            string `json:"mysqlx_crud_modify_view"`
	MysqlxCrudUpdate                                string `json:"mysqlx_crud_update"`
	MysqlxCursorClose                               string `json:"mysqlx_cursor_close"`
	MysqlxCursorFetch                               string `json:"mysqlx_cursor_fetch"`
	MysqlxCursorOpen                                string `json:"mysqlx_cursor_open"`
	MysqlxErrorsSent                                string `json:"mysqlx_errors_sent"`
	MysqlxErrorsUnknownMessageType                  string `json:"mysqlx_errors_unknown_message_type"`
	MysqlxExpectClose                               string `json:"mysqlx_expect_close"`
	MysqlxExpectOpen                                string `json:"mysqlx_expect_open"`
	MysqlxInitError                                 string `json:"mysqlx_init_error"`
	MysqlxMessagesSent                              string `json:"mysqlx_messages_sent"`
	MysqlxNoticeGlobalSent                          string `json:"mysqlx_notice_global_sent"`
	MysqlxNoticeOtherSent                           string `json:"mysqlx_notice_other_sent"`
	MysqlxNoticeWarningSent                         string `json:"mysqlx_notice_warning_sent"`
	MysqlxNotifiedByGroupReplication                string `json:"mysqlx_notified_by_group_replication"`
	MysqlxPort                                      string `json:"mysqlx_port"`
	MysqlxPrepDeallocate                            string `json:"mysqlx_prep_deallocate"`
	MysqlxPrepExecute                               string `json:"mysqlx_prep_execute"`
	MysqlxPrepPrepare                               string `json:"mysqlx_prep_prepare"`
	MysqlxRowsSent                                  string `json:"mysqlx_rows_sent"`
	MysqlxSessions                                  string `json:"mysqlx_sessions"`
	MysqlxSessionsAccepted                          string `json:"mysqlx_sessions_accepted"`
	MysqlxSessionsClosed                            string `json:"mysqlx_sessions_closed"`
	MysqlxSessionsFatalError                        string `json:"mysqlx_sessions_fatal_error"`
	MysqlxSessionsKilled                            string `json:"mysqlx_sessions_killed"`
	MysqlxSessionsRejected                          string `json:"mysqlx_sessions_rejected"`
	MysqlxSocket                                    string `json:"mysqlx_socket"`
	MysqlxSslAccepts                                string `json:"mysqlx_ssl_accepts"`
	MysqlxSslActive                                 string `json:"mysqlx_ssl_active"`
	MysqlxSslCipher                                 string `json:"mysqlx_ssl_cipher"`
	MysqlxSslCipherList                             string `json:"mysqlx_ssl_cipher_list"`
	MysqlxSslCtxVerifyDepth                         string `json:"mysqlx_ssl_ctx_verify_depth"`
	MysqlxSslCtxVerifyMode                          string `json:"mysqlx_ssl_ctx_verify_mode"`
	MysqlxSslFinishedAccepts                        string `json:"mysqlx_ssl_finished_accepts"`
	MysqlxSslServerNotAfter                         string `json:"mysqlx_ssl_server_not_after"`
	MysqlxSslServerNotBefore                        string `json:"mysqlx_ssl_server_not_before"`
	MysqlxSslVerifyDepth                            string `json:"mysqlx_ssl_verify_depth"`
	MysqlxSslVerifyMode                             string `json:"mysqlx_ssl_verify_mode"`
	MysqlxSslVersion                                string `json:"mysqlx_ssl_version"`
	MysqlxStmtCreateCollection                      string `json:"mysqlx_stmt_create_collection"`
	MysqlxStmtCreateCollectionIndex                 string `json:"mysqlx_stmt_create_collection_index"`
	MysqlxStmtDisableNotices                        string `json:"mysqlx_stmt_disable_notices"`
	MysqlxStmtDropCollection                        string `json:"mysqlx_stmt_drop_collection"`
	MysqlxStmtDropCollectionIndex                   string `json:"mysqlx_stmt_drop_collection_index"`
	MysqlxStmtEnableNotices                         string `json:"mysqlx_stmt_enable_notices"`
	MysqlxStmtEnsureCollection                      string `json:"mysqlx_stmt_ensure_collection"`
	MysqlxStmtExecuteMysqlx                         string `json:"mysqlx_stmt_execute_mysqlx"`
	MysqlxStmtExecuteSql                            string `json:"mysqlx_stmt_execute_sql"`
	MysqlxStmtExecuteXplugin                        string `json:"mysqlx_stmt_execute_xplugin"`
	MysqlxStmtGetCollectionOptions                  string `json:"mysqlx_stmt_get_collection_options"`
	MysqlxStmtKillClient                            string `json:"mysqlx_stmt_kill_client"`
	MysqlxStmtListClients                           string `json:"mysqlx_stmt_list_clients"`
	MysqlxStmtListNotices                           string `json:"mysqlx_stmt_list_notices"`
	MysqlxStmtListObjects                           string `json:"mysqlx_stmt_list_objects"`
	MysqlxStmtModifyCollectionOptions               string `json:"mysqlx_stmt_modify_collection_options"`
	MysqlxStmtPing                                  string `json:"mysqlx_stmt_ping"`
	MysqlxWorkerThreads                             string `json:"mysqlx_worker_threads"`
	MysqlxWorkerThreadsActive                       string `json:"mysqlx_worker_threads_active"`
	NotFlushedDelayedRows                           string `json:"not_flushed_delayed_rows"`
	OngoingAnonymousTransactionCount                string `json:"ongoing_anonymous_transaction_count"`
	OpenFiles                                       string `json:"open_files"`
	OpenStreams                                     string `json:"open_streams"`
	OpenTableDefinitions                            string `json:"open_table_definitions"`
	OpenTables                                      string `json:"open_tables"`
	OpenedFiles                                     string `json:"opened_files"`
	OpenedTableDefinitions                          string `json:"opened_table_definitions"`
	OpenedTables                                    string `json:"opened_tables"`
	PerformanceSchemaAccountsLost                   string `json:"performance_schema_accounts_lost"`
	PerformanceSchemaCondClassesLost                string `json:"performance_schema_cond_classes_lost"`
	PerformanceSchemaCondInstancesLost              string `json:"performance_schema_cond_instances_lost"`
	PerformanceSchemaDigestLost                     string `json:"performance_schema_digest_lost"`
	PerformanceSchemaFileClassesLost                string `json:"performance_schema_file_classes_lost"`
	PerformanceSchemaFileHandlesLost                string `json:"performance_schema_file_handles_lost"`
	PerformanceSchemaFileInstancesLost              string `json:"performance_schema_file_instances_lost"`
	PerformanceSchemaHostsLost                      string `json:"performance_schema_hosts_lost"`
	PerformanceSchemaIndexStatLost                  string `json:"performance_schema_index_stat_lost"`
	PerformanceSchemaLockerLost                     string `json:"performance_schema_locker_lost"`
	PerformanceSchemaMemoryClassesLost              string `json:"performance_schema_memory_classes_lost"`
	PerformanceSchemaMetadataLockLost               string `json:"performance_schema_metadata_lock_lost"`
	PerformanceSchemaMutexClassesLost               string `json:"performance_schema_mutex_classes_lost"`
	PerformanceSchemaMutexInstancesLost             string `json:"performance_schema_mutex_instances_lost"`
	PerformanceSchemaNestedStatementLost            string `json:"performance_schema_nested_statement_lost"`
	PerformanceSchemaPreparedStatementsLost         string `json:"performance_schema_prepared_statements_lost"`
	PerformanceSchemaProgramLost                    string `json:"performance_schema_program_lost"`
	PerformanceSchemaRwlockClassesLost              string `json:"performance_schema_rwlock_classes_lost"`
	PerformanceSchemaRwlockInstancesLost            string `json:"performance_schema_rwlock_instances_lost"`
	PerformanceSchemaSessionConnectAttrsLongestSeen string `json:"performance_schema_session_connect_attrs_longest_seen"`
	PerformanceSchemaSessionConnectAttrsLost        string `json:"performance_schema_session_connect_attrs_lost"`
	PerformanceSchemaSocketClassesLost              string `json:"performance_schema_socket_classes_lost"`
	PerformanceSchemaSocketInstancesLost            string `json:"performance_schema_socket_instances_lost"`
	PerformanceSchemaStageClassesLost               string `json:"performance_schema_stage_classes_lost"`
	PerformanceSchemaStatementClassesLost           string `json:"performance_schema_statement_classes_lost"`
	PerformanceSchemaTableHandlesLost               string `json:"performance_schema_table_handles_lost"`
	PerformanceSchemaTableInstancesLost             string `json:"performance_schema_table_instances_lost"`
	PerformanceSchemaTableLockStatLost              string `json:"performance_schema_table_lock_stat_lost"`
	PerformanceSchemaThreadClassesLost              string `json:"performance_schema_thread_classes_lost"`
	PerformanceSchemaThreadInstancesLost            string `json:"performance_schema_thread_instances_lost"`
	PerformanceSchemaUsersLost                      string `json:"performance_schema_users_lost"`
	PreparedStmtCount                               string `json:"prepared_stmt_count"`
	Queries                                         string `json:"queries"`
	Questions                                       string `json:"questions"`
	ReplicaOpenTempTables                           string `json:"replica_open_temp_tables"`
	RsaPublicKey                                    string `json:"rsa_public_key"`
	SecondaryEngineExecutionCount                   string `json:"secondary_engine_execution_count"`
	SelectFullJoin                                  string `json:"select_full_join"`
	SelectFullRangeJoin                             string `json:"select_full_range_join"`
	SelectRange                                     string `json:"select_range"`
	SelectRangeCheck                                string `json:"select_range_check"`
	SelectScan                                      string `json:"select_scan"`
	SlaveOpenTempTables                             string `json:"slave_open_temp_tables"`
	SlowLaunchThreads                               string `json:"slow_launch_threads"`
	SlowQueries                                     string `json:"slow_queries"`
	SortMergePasses                                 string `json:"sort_merge_passes"`
	SortRange                                       string `json:"sort_range"`
	SortRows                                        string `json:"sort_rows"`
	SortScan                                        string `json:"sort_scan"`
	SslAcceptRenegotiates                           string `json:"ssl_accept_renegotiates"`
	SslAccepts                                      string `json:"ssl_accepts"`
	SslCallbackCacheHits                            string `json:"ssl_callback_cache_hits"`
	SslCipher                                       string `json:"ssl_cipher"`
	SslCipherList                                   string `json:"ssl_cipher_list"`
	SslClientConnects                               string `json:"ssl_client_connects"`
	SslConnectRenegotiates                          string `json:"ssl_connect_renegotiates"`
	SslCtxVerifyDepth                               string `json:"ssl_ctx_verify_depth"`
	SslCtxVerifyMode                                string `json:"ssl_ctx_verify_mode"`
	SslDefaultTimeout                               string `json:"ssl_default_timeout"`
	SslFinishedAccepts                              string `json:"ssl_finished_accepts"`
	SslFinishedConnects                             string `json:"ssl_finished_connects"`
	SslServerNotAfter                               string `json:"ssl_server_not_after"`
	SslServerNotBefore                              string `json:"ssl_server_not_before"`
	SslSessionCacheHits                             string `json:"ssl_session_cache_hits"`
	SslSessionCacheMisses                           string `json:"ssl_session_cache_misses"`
	SslSessionCacheMode                             string `json:"ssl_session_cache_mode"`
	SslSessionCacheOverflows                        string `json:"ssl_session_cache_overflows"`
	SslSessionCacheSize                             string `json:"ssl_session_cache_size"`
	SslSessionCacheTimeouts                         string `json:"ssl_session_cache_timeouts"`
	SslSessionsReused                               string `json:"ssl_sessions_reused"`
	SslUsedSessionCacheEntries                      string `json:"ssl_used_session_cache_entries"`
	SslVerifyDepth                                  string `json:"ssl_verify_depth"`
	SslVerifyMode                                   string `json:"ssl_verify_mode"`
	SslVersion                                      string `json:"ssl_version"`
	TableLocksImmediate                             string `json:"table_locks_immediate"`
	TableLocksWaited                                string `json:"table_locks_waited"`
	TableOpenCacheHits                              string `json:"table_open_cache_hits"`
	TableOpenCacheMisses                            string `json:"table_open_cache_misses"`
	TableOpenCacheOverflows                         string `json:"table_open_cache_overflows"`
	TcLogMaxPagesUsed                               string `json:"tc_log_max_pages_used"`
	TcLogPageSize                                   string `json:"tc_log_page_size"`
	TcLogPageWaits                                  string `json:"tc_log_page_waits"`
	ThreadsCached                                   string `json:"threads_cached"`
	ThreadsConnected                                string `json:"threads_connected"`
	ThreadsCreated                                  string `json:"threads_created"`
	ThreadsRunning                                  string `json:"threads_running"`
	Uptime                                          string `json:"uptime"`
	UptimeSinceFlushStatus                          string `json:"uptime_since_flush_status"`
}
